# Generated by Django 4.2.1 on 2023-05-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_teste_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teste_empresa',
        ),
    ]
