# Generated by Django 4.2.1 on 2023-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_empresas_afiliacao_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas_afiliacao',
            name='cnpj',
            field=models.BigIntegerField(),
        ),
    ]
